src/Form/PhotosImageDeleteForm.php
<?php

namespace Drupal\photos\Form;

use Drupal\Core\Entity\ContentEntityDeleteForm;

/**
 * Defines a confirmation form for deleting images.
 */
class PhotosImageDeleteForm extends ContentEntityDeleteForm {

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'photos_image_confirm_delete';
  }

  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    return $this->t('Do you want to delete this image %title?', ['%title' => $this->entity->label()]);
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    return $this->t('Only do this if you are sure!');
  }

  /**
   * {@inheritdoc}
   */
  public function getConfirmText() {
    return $this->t('Delete it!');
  }

  /**
   * {@inheritdoc}
   */
  public function getCancelText() {
    return $this->t('Nevermind');
  }

  /**
   * {@inheritdoc}
   */
  protected function getRedirectUrl() {
    /** @var \Drupal\photos\PhotosImageInterface $entity */
    $entity = $this->getEntity();
    return $entity->getAlbumUrl();
  }

  /**
   * {@inheritdoc}
   */
  protected function logDeletionMessage() {
    /** @var \Drupal\photos\PhotosImageInterface $entity */
    $entity = $this->getEntity();
    $this->logger('photos')->notice('Deleted image %title.', ['%title' => $entity->label()]);
  }

}

templates/legacy/photos_album_links.html.twig
{#
/**
 * @file
 * Formats album links.
 */
#}
{% if links.link or links.count %}
  <div class="photos-album-links">
    <div class="photos-link-info">
      {% trans %}
        {{ links.count }} image
      {% plural links.count %}
        {{ links.count }} images
      {% endtrans %}

      {{ links_display }}
    </div>
    <div class="photos-link-sort">
      <span>{{ 'Sort by'|t }}:</span>
      {{ links_sort }}
    </div>
    {% if links.limit %}
      <div class="photos-link-limit">
        <span>{{ 'Limit'|t }}:</span>
        {{ links_limit }}
      </div>
    {% endif %}
  </div>
{% endif %}

templates/legacy/photos_album_view.html.twig
{#
/**
 * @file
 * Default theme implementation for photos to display images in a list or grid.
 *
 * Available variables:
 * - album: The album object.
 * - node: The node object.
 * - pager: The album pager.
 *
 * @ingroup themeable
 */
#}
{% if album.album_url is not empty or album.node_edit_url is not empty %}
<div class="photos-album-menu">
  {% if album.access.edit %}
    {{ album.node_edit_url }}
    {{ album.image_management_url }}
  {% endif %}
</div>
{% endif %}
{% if node_type == 'photos' %}
  <div class="photos-album-header">
    {% if album.cover %}
      <div class="photos-album-cover">
        {{ album.cover }}
      </div>
    {% endif %}
    <div class="photos-album-right">
      {% trans %}
        {{ node.album.count }} image
      {% plural node.album.count %}
        {{ node.album.count }} images
      {% endtrans %}
      <div class="submitted">
        {% trans %}Submitted by {{ author_name }} on {{ date }}{% endtrans %}
      </div>
    </div>
  </div>
{% endif %}

{{ album.links }}

{{ pager }}

{% if display_type == 'grid' %}
  <div class="photos-album-grid">
    <div class="photos-row photos-row-0">
      {% for view in album.view %}
        <div class="photos-col photos-col-{{ loop.index }}" style="{{ grid_col_width }}">
          {{ view }}
        </div>
        {% if loop.index % grid_col_count == 0 %}
          </div>
          <div class="photos-row {{ 'photos-row-' ~ loop.index // grid_col_count }}">
        {% endif %}
      {% endfor %}
    </div>
  </div>
{% else %}
  {% for view in album.view %}
    {{ view }}
  {% endfor %}
{% endif %}

{{ pager }}

templates/legacy/photos_default.html.twig
{#
/**
 * @file
 * Formats default layout.
 */
#}
<div id="photos-default">
  {% if content.user.image %}
    <h2>{{ 'My latest images'|t }}</h2>
    {{ user_images }}
  {% endif %}
  {% if content.user.album %}
    <h2>{{ 'My latest albums'|t }}</h2>
    {{ user_albums }}
  {% endif %}
  {% if content.site.image %}
    <h2>{{ 'Latest images'|t }}</h2>
    {{ site_images }}
  {% endif %}
  {% if content.site.album %}
    <h2>{{ 'Latest albums'|t }}</h2>
    {{ site_albums }}
  {% endif %}
</div>

templates/legacy/photos_image_colorbox_link.html.twig
{#
/**
 * @file
 * Colorbox gallery image links with optional cover image.
 */
#}
<a href="{{ image_url }}" class="colorbox" data-colorbox-gallery="photos-gallery-{{ nid }}" title="{{ image_title }}">{{ image }}</a>

templates/legacy/photos_image_html.html.twig
{#
/**
 * @file
 * Photos image wrapper.
 */
#}
{% if image.href is empty %}
  {{ image.view }}
{% else %}
  <div class="photos-image-html">
    <a href="{{ image.href }}">{{ image.view }}</a>
    {% if image.colorbox %}
      {# // @todo original image link. #}
      <a class="photos-image-html-colorbox colorbox" rel="colorbox_{{ image.album_id }}" href="{{ image.uri }}" title="{{ title }}">
        view original
      </a>
    {% endif %}
  </div>
{% endif %}

templates/legacy/photos_image_view.html.twig
{#
/**
 * @file
 * Formats single image view on image page and list views.
 */
#}
{% if display_type == 'list' %}
  <div class="photos-image-list-view" {{ image.ajax.del_id }}>
    <div class="photos-list-view-thumb">
      <a href="{{ image.url }}#image-load">{{ image.view }}</a>
    </div>
    <h2 class="photos-list-view-title{{ image.class.title_class }}"{{ image.id.title_edit }}>
      {{ image.title }}
    </h2>
    <div class="photos-list-view-des{{ image.class.des_class }}" {{ image.id.des_edit }}>{{ image.description }}</div>
    <div class="photos-list-view-info">

      {% if image.ajax.del_link %}
        {{ image.ajax.del_link }}
      {% endif %}

      {% if image.ajax.edit_link %}
        {{ image.ajax.edit_link }}
      {% endif %}

      {% if image.links.info %}
        {{ image.links.info }}
      {% endif %}

      {% if image.links.count %}
        <span class="photos-visits">
          {{ image.links.count }}
        </span>
      {% endif %}

      {% if image.links.cover %}
        {{ image.links.cover }}
      {% endif %}

      {% if image.links.comment %}
        {{ image.links.comment }}
      {% endif %}

    </div>
  </div>

{% else %}

  <div id="image-load" class="image-load">
    <div class="photos-view-links">
      <div class="photo-links-info">

        {% if image.ajax.del_link %}
          {{ image.ajax.del_link }}
        {% endif %}

        {% if image.ajax.edit_link %}
          {{ image.ajax.edit_link }}
        {% endif %}

        {% if not image.disable_photos_image_count %}
          {% trans %}
            {{ image.count }} visit
          {% plural image.count %}
            {{ image.count }} visits
          {% endtrans %}
        {% endif %}

        {% if image.links.comment %}
          {{ image.links.comment }}
        {% endif %}

        {% if image.links.cover %}
          {{ image.links.cover }}
        {% endif %}

        {% if image.links.more %}
          {{ image.links.more }}
        {% endif %}

      </div>
    </div>
    <div class="photo-link-pager">
      {% if image.links.pager.prevUrl %}
        <div class="photo-pager-left">
          <a href="{{ image.links.pager.prevUrl }}#image-load">&laquo; {{ 'previous'|t }}</a>
        </div>
      {% endif %}

      {% if image.links.pager.nextUrl %}
        <div class="photo-pager-right">
          <a href="{{ image.links.pager.nextUrl }}#image-load">{{ 'next'|t }} &raquo;</a>
        </div>
      {% endif %}
    </div>
    <div class="photos-image">{{ image.view }}</div>
  </div>
  {% if image.comment.view %}
    {{ image.comment.view }}
  {% endif %}
  {% if image.comment.box %}
    {{ image.comment.box }}
  {% endif %}
{% endif %}